"""
This type stub file was generated by pyright.
"""

class CryptoWarning(Warning):
    """Base class for PyCrypto warnings"""
    ...


class CryptoDeprecationWarning(DeprecationWarning, CryptoWarning):
    """Base PyCrypto DeprecationWarning class"""
    ...


class CryptoRuntimeWarning(RuntimeWarning, CryptoWarning):
    """Base PyCrypto RuntimeWarning class"""
    ...


class RandomPool_DeprecationWarning(CryptoDeprecationWarning):
    """Issued when Crypto.Util.randpool.RandomPool is instantiated."""
    ...


class ClockRewindWarning(CryptoRuntimeWarning):
    """Warning for when the system clock moves backwards."""
    ...


class GetRandomNumber_DeprecationWarning(CryptoDeprecationWarning):
    """Issued when Crypto.Util.number.getRandomNumber is invoked."""
    ...


class PowmInsecureWarning(CryptoRuntimeWarning):
    """Warning for when _fastmath is built without mpz_powm_sec"""
    ...


