"""
This type stub file was generated by pyright.
"""

from Crypto.Util.py3compat import *
from Crypto.Hash.hashalgo import HashAlgo

"""SHA-1 cryptographic hash algorithm.

SHA-1_ produces the 160 bit digest of a message.

    >>> from Crypto.Hash import SHA
    >>>
    >>> h = SHA.new()
    >>> h.update(b'Hello')
    >>> print h.hexdigest()

*SHA* stands for Secure Hash Algorithm.

This algorithm is not considered secure. Do not use it for new designs.

.. _SHA-1: http://csrc.nist.gov/publications/fips/fips180-2/fips180-2.pdf
"""
_revision__ = ...
__all__ = ['new', 'digest_size', 'SHA1Hash']
hashFactory = ...
class SHA1Hash(HashAlgo):
    """Class that implements a SHA-1 hash
    
    :undocumented: block_size
    """
    oid = ...
    digest_size = ...
    block_size = ...
    def __init__(self, data=...) -> None:
        ...
    
    def new(self, data=...): # -> SHA1Hash:
        ...
    


def new(data=...): # -> SHA1Hash:
    """Return a fresh instance of the hash object.

    :Parameters:
       data : byte string
        The very first chunk of the message to hash.
        It is equivalent to an early call to `SHA1Hash.update()`.
        Optional.

    :Return: A `SHA1Hash` object
    """
    ...

digest_size = ...
block_size = ...
