"""
This type stub file was generated by pyright.
"""

from os import urandom

__all__ = ['new', 'get_random_bytes']
class _UrandomRNG:
     def read(self, n): # -> bytes:
          """Return a random byte string of the desired size."""
          ...
     
     def flush(self): # -> None:
          """Method provided for backward compatibility only."""
          ...
     
     def reinit(self): # -> None:
          """Method provided for backward compatibility only."""
          ...
     
     def close(self): # -> None:
          """Method provided for backward compatibility only."""
          ...
     


def new(*args, **kwargs): # -> _UrandomRNG:
     """Return a file-like object that outputs cryptographically random bytes."""
     ...

def atfork(): # -> None:
     ...

get_random_bytes = ...
