"""
This type stub file was generated by pyright.
"""

"""Digital signature protocols

A collection of standardized protocols to carry out digital signatures.

:undocumented: __revision__, __package__
"""
__all__ = ['PKCS1_v1_5', 'PKCS1_PSS']
__revision__ = ...
