"""
This type stub file was generated by pyright.
"""

__revision__ = ...
__all__ = ['ceil_shift', 'ceil_div', 'floor_div', 'exact_log2', 'exact_div']
def ceil_shift(n, b): # -> int:
    """Return ceil(n / 2**b) without performing any floating-point or division operations.

    This is done by right-shifting n by b bits and incrementing the result by 1
    if any '1' bits were shifted out.
    """
    ...

def ceil_div(a, b): # -> int:
    """Return ceil(a / b) without performing any floating-point operations."""
    ...

def floor_div(a, b): # -> int:
    ...

def exact_log2(num): # -> int:
    """Find and return an integer i >= 0 such that num == 2**i.

    If no such integer exists, this function raises ValueError.
    """
    ...

def exact_div(p, d, allow_divzero=...): # -> int:
    """Find and return an integer n such that p == n * d

    If no such integer exists, this function raises ValueError.

    Both operands must be integers.

    If the second operand is zero, this function will raise ZeroDivisionError
    unless allow_divzero is true (default: False).
    """
    ...

