"""
This type stub file was generated by pyright.
"""

from Crypto.Util.py3compat import *
from Crypto.PublicKey import _fastmath
from ._number_new import *

__revision__ = ...
bignum = int
if _fastmath is not None and not _fastmath.HAVE_DECL_MPZ_POWM_SEC:
    ...
def size(N): # -> int:
    """size(N:long) : int
    Returns the size of the number N in bits.
    """
    ...

def getRandomNumber(N, randfunc=...):
    """Deprecated.  Use getRandomInteger or getRandomNBitInteger instead."""
    ...

def getRandomInteger(N, randfunc=...): # -> Any | Literal[0]:
    """getRandomInteger(N:int, randfunc:callable):long
    Return a random number with at most N bits.

    If randfunc is omitted, then Random.new().read is used.

    This function is for internal use only and may be renamed or removed in
    the future.
    """
    ...

def getRandomRange(a, b, randfunc=...):
    """getRandomRange(a:int, b:int, randfunc:callable):long
    Return a random number n so that a <= n < b.

    If randfunc is omitted, then Random.new().read is used.

    This function is for internal use only and may be renamed or removed in
    the future.
    """
    ...

def getRandomNBitInteger(N, randfunc=...):
    """getRandomInteger(N:int, randfunc:callable):long
    Return a random number with exactly N-bits, i.e. a random number
    between 2**(N-1) and (2**N)-1.

    If randfunc is omitted, then Random.new().read is used.

    This function is for internal use only and may be renamed or removed in
    the future.
    """
    ...

def GCD(x, y):
    """GCD(x:long, y:long): long
    Return the GCD of x and y.
    """
    ...

def inverse(u, v): # -> int:
    """inverse(u:long, v:long):long
    Return the inverse of u mod v.
    """
    ...

def getPrime(N, randfunc=...):
    """getPrime(N:int, randfunc:callable):long
    Return a random N-bit prime number.

    If randfunc is omitted, then Random.new().read is used.
    """
    ...

def getStrongPrime(N, e=..., false_positive_prob=..., randfunc=...):
    """getStrongPrime(N:int, e:int, false_positive_prob:float, randfunc:callable):long
    Return a random strong N-bit prime number.
    In this context p is a strong prime if p-1 and p+1 have at
    least one large prime factor.
    N should be a multiple of 128 and > 512.

    If e is provided the returned prime p-1 will be coprime to e
    and thus suitable for RSA where e is the public exponent.

    The optional false_positive_prob is the statistical probability
    that true is returned even though it is not (pseudo-prime).
    It defaults to 1e-6 (less than 1:1000000).
    Note that the real probability of a false-positive is far less. This is
    just the mathematically provable limit.

    randfunc should take a single int parameter and return that
    many random bytes as a string.
    If randfunc is omitted, then Random.new().read is used.
    """
    ...

def isPrime(N, false_positive_prob=..., randfunc=...): # -> Literal[1, 0]:
    """isPrime(N:long, false_positive_prob:float, randfunc:callable):bool
    Return true if N is prime.

    The optional false_positive_prob is the statistical probability
    that true is returned even though it is not (pseudo-prime).
    It defaults to 1e-6 (less than 1:1000000).
    Note that the real probability of a false-positive is far less. This is
    just the mathematically provable limit.

    If randfunc is omitted, then Random.new().read is used.
    """
    ...

def long_to_bytes(n, blocksize=...): # -> bytes:
    """long_to_bytes(n:long, blocksize:int) : string
    Convert a long integer to a byte string.

    If optional blocksize is given and greater than zero, pad the front of the
    byte string with binary zeros so that the length is a multiple of
    blocksize.
    """
    ...

def bytes_to_long(s): # -> Any | Literal[0]:
    """bytes_to_long(string) : long
    Convert a byte string to a long integer.

    This is (essentially) the inverse of long_to_bytes().
    """
    ...

def long2str(n, blocksize=...): # -> bytes:
    ...

def str2long(s): # -> Any | Literal[0]:
    ...

sieve_base = ...
